Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -41,6 +41,11 @@ inputs:
     type: boolean
     required: false
     default: 'false'
+  remote:
+    description: 'Errors repaired with clang-tidy push changes to remote repo if true'
+    type: boolean
+    required: false
+    default: 'false'
 
 runs:
   using: composite
@@ -178,7 +183,7 @@ runs:
                 echo -e "\nFound Include Path(s):\n${includes}\n";
                 for i in ${includes[@]}; do
                   count2=$((include_count++));
-                  header=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f \( -path "*/$(dirname ${i})/*" -o -path "*" \) -name "$(basename ${i})" -print);
+                  header=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f \( -path "*/$(dirname ${i})/*" -o -path "*" \) -name "$(basename ${i})" -print -quit);
                   for h in "${header[@]}"; do
                     echo "$(dirname ${h})" >> "$(dirname ${f})/${included1}";
                   done;
@@ -239,46 +244,44 @@ runs:
             if ${{ inputs.content }}; then
               echo -e "\n####################\n\tFILE CONTENT (${count1})\n####################\n";
               sudo find $(dirname ${f}) -type f -name $(basename ${f}) -exec batcat --theme=ansi --paging=never --show-all --color=always --style=full "{}" \;
-            fi;
-            if ! ${{ inputs.include }}; then
+            fi;  
+            includes=$(sudo find $(dirname ${f}) -name $(basename ${f}) -exec sed -n 's/^#include <\(.*\)>/\1/p; s/^#include "\(.*\)"/\1/p' "{}" \;);
+            included1='include_file.txt'
+            included2='include_paths.txt'
+            if [[ -n ${includes} ]]; then
+              echo -e "\n# Found Include Path(s):\n${includes}\n";
+              include='';
+              for i in ${includes[@]}; do
+                include+=' -I';
+                count2=$((include_count++));
+                header=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f \( -path "*/$(dirname ${i})/*" -o -path "*" \) -name "$(basename ${i})" -print -quit);
+                for h in ${header[@]}; do
+                  echo "$(dirname ${h})" >> "$(dirname ${f})/${included1}";
+                  include+="$(dirname ${h})";
+                done;
+              done;
+              if [[ -f "$(dirname ${f})/${included1}" ]]; then
+                awk '!seen[$0]++' "$(dirname ${f})/${included1}" > "$(dirname ${f})/${included2}";
+              fi;
+              if [[ -n ${header} ]] && [[ -n ${include} ]]; then
+                if ${{ inputs.content }}; then
+                  included3=$(dirname ${f})/${included2}
+                  echo -e "\n####################\n\tFILE PATH(S) (${count2})\n####################\n";
+                  batcat --theme=ansi --paging=never --show-all --color=always --style=full "${included3}";
+                fi;
+                echo -e "\n\n####################\nCLANG-TIDY INCLUDE FILES ANALYZER (${count2})\n####################\n\nFinal File: ${i}\n\n";
+                clang-tidy "${f}" --config-file="${clang_file}" --fix-errors --fix-notes -- "$(echo -n ${include})" |& tee -a "${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log" || echo -e "\n####################\nCLANG-TIDY FOUND ERROR(S)\n####################\n" && file_error=1;
+                if [[ ${file_error} == 0 ]]; then
+                  echo -e "\n####################\nCLANG-TIDY NO ERRORS FOUND ${f}\n####################\n";
+                fi;
+              else 
+                echo -e "\n\n####################\nCLANG-TIDY INCLUDE FILE(S) FOR $(basename ${f}) NOT FOUND\n####################\n\n";
+              fi;
+            else
               echo -e "\n\n####################\nCLANG-TIDY ERROR ANALYZER (${count1})\n####################\n\n";
               clang-tidy "${f}" --config-file="${clang_file}" --fix-errors --fix-notes --quiet |& tee -a "${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log" || echo -e "\n####################\nCLANG-TIDY FOUND ERROR(S)\n####################\n" && file_error=1;
               if [[ ${file_error} == 0 ]]; then
                 echo -e "\n####################\nCLANG-TIDY NO ERRORS FOUND ${f}\n####################\n";
-              fi;
-            elif ${{ inputs.include }}; then
-              includes=$(sudo find $(dirname ${f}) -name $(basename ${f}) -exec sed -n 's/^#include <\(.*\)>/\1/p; s/^#include "\(.*\)"/\1/p' "{}" \;);
-              included1='include_file.txt'
-              included2='include_paths.txt'
-              if [[ -n ${includes} ]]; then
-                echo -e "\n# Found Include Path(s):\n${includes}\n";
-                for i in ${includes[@]}; do
-                  include=''
-                  count2=$((include_count++));
-                  header=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f \( -path "*/$(dirname ${i})/*" -o -path "*" \) -name "$(basename ${i})" -print);
-                  for h in ${header[@]}; do
-                    echo "$(dirname ${h})" >> "$(dirname ${f})/${included1}";
-                    include+=' -I'
-                    include+="$(dirname ${h})"
-                  done;
-                done;
-                if [[ -f "$(dirname ${f})/${included1}" ]]; then
-                  awk '!seen[$0]++' "$(dirname ${f})/${included1}" > "$(dirname ${f})/${included2}";
-                fi;
-                if [[ -n ${header} ]] && [[ -n ${include} ]]; then
-                  if ${{ inputs.content }}; then
-                    included3=$(dirname ${f})/${included2}
-                    echo -e "\n####################\n\tFILE PATH(S) (${count2})\n####################\n";
-                    batcat --theme=ansi --paging=never --show-all --color=always --style=full "${included3}";
-                  fi;
-                  echo -e "\n\n####################\nCLANG-TIDY INCLUDE FILES ANALYZER (${count2})\n####################\n\nFinal File: ${i}\n\n";
-                  clang-tidy "${f}" --config-file="${clang_file}" --fix-errors --fix-notes -- ${include} -std=c++20 |& tee -a "${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log" || echo -e "\n####################\nCLANG-TIDY FOUND ERROR(S)\n####################\n" && file_error=1;
-                  if [[ ${file_error} == 0 ]]; then
-                    echo -e "\n####################\nCLANG-TIDY NO ERRORS FOUND ${f}\n####################\n";
-                  fi;
-                else 
-                  echo -e "\n\n####################\nCLANG-TIDY INCLUDE FILE(S) FOR $(basename ${f}) NOT FOUND\n####################\n\n";
-                fi;
               fi;
             fi;
           done;
@@ -481,6 +484,25 @@ runs:
           ./${{ inputs.filename }}_error.log
         name: Check File Action Errors Report For ${{ inputs.filename }} File(s).
         tag_name: ${{ github.run_id }}
+
+
+    - name: Repo Update
+      if: inputs.remote != 'false' && inputs.clangfix != 'false'
+      uses: actions/checkout@v5
+      with:
+        clean: false
+
+      
+    - name: Repo Restore
+      if: inputs.remote != 'false' && inputs.clangfix != 'false' 
+      run: | 
+        date > generated.txt
+        git config --global user.email "${GitHubMail}"
+        git config --global user.name "${GitHubName}"
+        git config --global credential.helper store
+        git add . 
+        git commit -m "Clang-tidy fixed files with errors" 
+        git push
 
 
     - name: Filename Check
