Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -96,9 +96,15 @@ runs:
             shellcheck=$(find $(dirname ${f}) -type f -name "*.sh" -print);
             echo -e "\n\n######\n\t SHELLCHECK ERROR ANALYZER ($count3) \n######\n";
             shellcheck --norc --severity=error ${f};
+            if [ $? -eq 0 ]; then
+              echo -e "\n\n######\n\t SHELLCHECK NO ERRORS FOUND ( $(basename ${s}) ) \n######\n";
+            fi;
             for s in ${shellcheck[@]}; do
-              echo -e "\n\n######\n\t ANALYZING FOR ERROR(S) ($count3) \n######\n";
-              shellcheck --norc --severity=error --external-sources --check-sourced ${s} 2>/dev/null;
+              echo -e "\n\n######\n\t ANALYZING ( $(basename ${s}) ) FOR ERROR(S) ($count3) \n######\n";
+              shellcheck --norc --severity=error --external-sources --check-sourced ${s};
+              if [ $? -eq 0 ]; then
+                echo -e "\n\n######\n\t SHELLCHECK NO ERRORS FOUND ( $(basename ${s}) ) \n######\n";
+              fi;
             done;
             if ${{ inputs.content }}; then
               echo -e "\n######\n FILE CONTENT \n######\n";
@@ -270,9 +276,15 @@ runs:
             shellcheck=$(sudo find $(dirname ${f}) -type f -name "*.sh" -print);
             echo -e "\n\n######\n\t SHELLCHECK ERROR ANALYZER ($count3) \n######\n";
             shellcheck --norc --severity=error ${f};
+            if [ $? -eq 0 ]; then
+              echo -e "\n\n######\n\t SHELLCHECK NO ERRORS FOUND ( $(basename ${s}) ) \n######\n";
+            fi;
             for s in ${shellcheck[@]}; do
-              echo -e "\n\n######\n\t ANALYZING FOR ERROR(S) ($count3) \n######\n";
-              shellcheck --norc --severity=error --external-sources --check-sourced ${s} 2>/dev/null;
+              echo -e "\n\n######\n\t ANALYZING ( $(basename ${s}) ) FOR ERROR(S) ($count3) \n######\n";
+              shellcheck --norc --severity=error --external-sources --check-sourced ${s};
+              if [ $? -eq 0 ]; then
+                echo -e "\n\n######\n\t SHELLCHECK NO ERRORS FOUND ( $(basename ${s}) ) \n######\n";
+              fi;
             done;
             if ${{ inputs.content }}; then
               echo -e "\n######\n FILE CONTENT \n######\n";
@@ -395,7 +407,7 @@ runs:
       shell: bash
       continue-on-error: true
 
-    - name: Directory Contents
+    - name: Directory Contains
       if: inputs.filename != '' && inputs.content != false
       run: |
         file_type=$(echo ${{ inputs.filename }} | sed 's/.*\.\([^.]*\)$/\1/');
