Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -231,7 +231,7 @@ runs:
             echo -e "\n####################\n\tclang-file found copying...\n####################\n";
             sudo cp -vf "${file_path}" "${clang_file}";
           fi;
-          echo -e "\nFound File Path(s):\n${files}\n\n";
+          echo -e "\n# Found File Path(s)\n${files}\n\n";
           for f in ${files[@]}; do
             count1=$((file_count++));
             echo -e "\n####################\n\tFILE PATH (${count1})\n####################\n";
@@ -240,25 +240,26 @@ runs:
               echo -e "\n####################\n\tFILE CONTENT (${count1})\n####################\n";
               sudo find $(dirname ${f}) -type f -name $(basename ${f}) -exec batcat --theme=ansi --paging=never --show-all --color=always --style=full "{}" \;
             fi;
-           # if ! ${{ inputs.include }}; then
+            if ! ${{ inputs.include }}; then
               echo -e "\n\n####################\nCLANG-TIDY ERROR ANALYZER (${count1})\n####################\n\n";
               clang-tidy "${f}" --config-file="${clang_file}" --fix-errors --fix-notes --quiet |& tee -a "${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log" || echo -e "\n####################\nCLANG-TIDY FOUND ERROR(S)\n####################\n" && file_error=1;
-            if [[ ${file_error} == 0 ]]; then
-              echo -e "\n####################\nCLANG-TIDY NO ERRORS FOUND ${f}\n####################\n";
-            fi;
-            if ${{ inputs.include }}; then
+              if [[ ${file_error} == 0 ]]; then
+                echo -e "\n####################\nCLANG-TIDY NO ERRORS FOUND ${f}\n####################\n";
+              fi;
+            elif ${{ inputs.include }}; then
               includes=$(sudo find $(dirname ${f}) -name $(basename ${f}) -exec sed -n 's/^#include <\(.*\)>/\1/p; s/^#include "\(.*\)"/\1/p' "{}" \;);
               included1='include_file.txt'
               included2='include_paths.txt'
               if [[ -n ${includes} ]]; then
-                echo -e "\nFound Include Path(s):\n${includes}\n";
+                echo -e "\n# Found Include Path(s):\n${includes}\n";
                 for i in ${includes[@]}; do
-                  include='';
+                  include=''
                   count2=$((include_count++));
-                  header=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f \( -path "*/$(dirname ${i})/*" -o -path "*" \) -name "$(basename ${i})" -print -quit);
+                  header=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f \( -path "*/$(dirname ${i})/*" -o -path "*" \) -name "$(basename ${i})" -print);
                   for h in ${header[@]}; do
                     echo "$(dirname ${h})" >> "$(dirname ${f})/${included1}";
-                    include+=" -I$(dirname ${h})";
+                    include+=' -I'
+                    include+="$(dirname ${h})"
                   done;
                 done;
                 if [[ -f "$(dirname ${f})/${included1}" ]]; then
@@ -282,7 +283,7 @@ runs:
             fi;
           done;
           if [[ -f "$(dirname ${f})/${included2}" ]]; then
-            echo -e "\n${include}\n";
+            echo -e "# Include File(s) List:\n\n${include}\n\n";
             rm -vf "$(dirname ${f})/${included1}" "$(dirname ${f})/${included2}" 2>/dev/null;
           fi;
           echo -e "\nTotal number of ${{ inputs.filename }} file(s) checked is: ${count1}\n";
