Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -136,15 +136,12 @@ runs:
             content=$(find $(dirname ${f}) -type f -name $(basename ${f}) -exec cat {} \;);
             makefile=$(find $(dirname ${f}) -type f \( -name "*.mk" -o -iname "Makefile" \) -print);
             echo -e "\n##########\n\tCHECKMAKE ERROR ANALYZER ($count4)\n##########\n";
-            checkmake ${f} || errorcode=$? && echo "\nScan Completed\nCheckmake error code ($errorcode)";
+            checkmake ${f} && echo -e "\n##########\n\tCHECKMAKE ($(basename ${f})) SCAN FOUND NO ERRORS\n##########\n" || if [ $? -eq 1 ]; then errorcode=$?; echo -e "\nScan Completed With Errors\nCheckmake exit code ($errorcode)"; fi;
             for m in ${makefile[@]}; do
               count4=$((makefile_count++));
               echo -e "\n\n##########\n\tANALYZING FILE(S) FOR ERROR(S) ($count4)\n##########\n";
-              checkmake ${m} || errorcode=$? && echo "\nScan Completed\nCheckmake error code ($errorcode)";
+              checkmake ${m} && echo -e "\n##########\n\tCHECKMAKE ($(basename ${f})) SCAN FOUND NO ERRORS\n##########\n" || if [ $? -eq 1 ]; then errorcode=$?; echo -e "\nScan Completed With Errors\nCheckmake exit code ($errorcode)"; fi;
             done;
-            if [ $? -eq 0 ]; then
-                echo -e "\n##########\n\tCHECKMAKE NO ERRORS FOUND ( $(basename ${s}) )\n##########\n";
-            fi;
             if ${{ inputs.content }}; then
               echo -e "\n##########\n\tFILE CONTENT\n##########\n";
               echo -e "\n${content}\n";
@@ -323,15 +320,12 @@ runs:
             content=$(sudo find $(dirname ${f}) -type f -name $(basename ${f}) -exec cat {} \;);
             makefile=$(sudo find $(dirname ${f}) -type f \( -name "*.mk" -o -iname "Makefile" \) -print);
             echo -e "\n##########\n\tCHECKMAKE ERROR ANALYZER ($count4)\n##########\n";
-            checkmake ${f} || errorcode=$? && echo "\nScan Completed\nCheckmake error code ($errorcode)";
+            checkmake ${f} && echo -e "\n##########\n\tCHECKMAKE ($(basename ${f})) SCAN FOUND NO ERRORS\n##########\n" || if [ $? -eq 1 ]; then errorcode=$?; echo -e "\nScan Completed With Errors\nCheckmake exit code ($errorcode)"; fi;
             for m in ${makefile[@]}; do
               count4=$((makefile_count++));
               echo -e "\n\n##########\n\tANALYZING FILE(S) FOR ERROR(S) ($count4)\n##########\n";
-              checkmake ${m} || errorcode=$? && echo "\nScan Completed\nCheckmake error code ($errorcode)";
+              checkmake ${m} && echo -e "\n##########\n\tCHECKMAKE ($(basename ${f})) SCAN FOUND NO ERRORS\n##########\n" || if [ $? -eq 1 ]; then errorcode=$?; echo -e "\nScan Completed With Errors\nCheckmake exit code ($errorcode)"; fi;
             done;
-            if [ $? -eq 0 ]; then
-                echo -e "\n##########\n\tCHECKMAKE NO ERRORS FOUND ( $(basename ${s}) )\n##########\n";
-            fi;
             if ${{ inputs.content }}; then
               echo -e "\n##########\n\tFILE CONTENT\n##########\n";
               echo -e "\n${content}\n";
