Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -33,25 +33,23 @@ runs:
       shell: bash
       continue-on-error: true
 
-    - name: Start From Root
+    - name: Start From Check
       run: |
         if ${{ inputs.rootdir }} && [[ ${{ inputs.filename != '' }} ]]; then
            echo -e "\n###### NOTE: Search will start from rootdir (/) ######\n";
            echo "FILE_PATH=/" >> ${GITHUB_ENV};
-           echo "SUDO_FIND=sudo find" >> ${GITHUB_ENV};
         else
-           echo -e "\n###### NOTE: Search will start from ${GITHUB_dirname} ######\n";
+           echo -e "\n###### NOTE: Search will start from ${GITHUB_WORKSPACE} ######\n";
            echo "FILE_PATH=${GITHUB_WORKSPACE}" >> ${GITHUB_ENV};
-           echo "SUDO_FIND=find" >> ${GITHUB_ENV};
         fi
       shell: bash
       continue-on-error: true
 
     - name: Check Filename
-      if: inputs.filename != ''
+      if: inputs.filename != '' && inputs.rootdir == false
       run: |
         export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
-        files=$($SUDO_FIND ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "${{ inputs.filename }}" -o -name "${{ inputs.filename }}" -print);
+        files=$(find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "${{ inputs.filename }}" -o -name "${{ inputs.filename }}" -print);
         file_type=$(echo ${{ inputs.filename }} | sed 's/.*\.\([^.]*\)$/\1/');
         file_count=1
         include_count=1
@@ -62,17 +60,17 @@ runs:
             for f in ${files[@]}; do
               count1=$((file_count++));
               echo -e "\n###### FILE PATH ($count1) ######\n";
-              $SUDO_FIND $(dirname ${f}) -type f -name $(basename ${f}) -print;
+              find $(dirname ${f}) -type f -name $(basename ${f}) -print;
               echo -e "\n###### FILE CONTENT ($count1) ######\n";
-              $SUDO_FIND $(dirname ${f}) -type f -name $(basename ${f}) -exec cat {} \; 
+              find $(dirname ${f}) -type f -name $(basename ${f}) -exec cat {} \; 
               echo -e "\n\n###### CPPCHECK ERROR ANALYZER ($count1) ######\n";
               cppcheck --verbose --force --enable=all --suppress=missingIncludeSystem --std=c++11 --report-progress --quiet ${f}
-              includes=$($SUDO_FIND $(dirname ${f}) -name $(basename ${f}) -exec sed -n 's/^#include <\(.*\)>/\1/p; s/^#include "\(.*\)"/\1/p' {} \;)      
+              includes=$(find $(dirname ${f}) -name $(basename ${f}) -exec sed -n 's/^#include <\(.*\)>/\1/p; s/^#include "\(.*\)"/\1/p' {} \;)      
               if [[ -n ${includes} ]]; then
                 echo -e "\nFound Include Path(s): \n${includes}\n";
                 for i in ${includes[@]}; do
                   count2=$((include_count++));
-                  header=$($SUDO_FIND $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f -path "*/$(dirname ${i})*" -name "$(basename ${i})" -o -name "$(basename ${i})" -print -quit) 2>/dev/null;
+                  header=$(find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f -path "*/$(dirname ${i})*" -name "$(basename ${i})" -o -name "$(basename ${i})" -print -quit) 2>/dev/null;
                   if [[ -f ${header} ]]; then
                     echo -e "\n###### CPPCHECK HEADER FILE ($count2) ######\n${i}\n";
                     cppcheck --verbose --force --enable=all --std=c++11 --report-progress --suppress=missingIncludeSystem ${header} ${f}
@@ -89,7 +87,7 @@ runs:
         elif [ ${file_type} = 'sh' ] && [[ -n ${files} ]]; then
           for f in ${files[@]}; do
             count3=$((shellcheck_count++));
-            shellcheck=$($SUDO_FIND $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f -path "*/$(dirname ${f})*" -name "$(basename ${i})" -print -quit) 2>/dev/null;
+            shellcheck=$(find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f -path "*/$(dirname ${f})*" -name "$(basename ${i})" -print -quit) 2>/dev/null;
             echo -e "\n\n###### SHELLCHECK ERROR ANALYZER ($count3) ######\n";
             for s in ${shellcheck[@]}; do
               echo -e "\n\n###### ANALYZING FOR ERROR(S) ($count3) ######\n";
@@ -102,7 +100,7 @@ runs:
         elif [ ${file_type} = 'Makefile' ] || [ ${file_type} = 'makefile' ] || [ ${file_type} = 'mk' ] && [[ -n ${files} ]]; then
           for f in ${files[@]}; do
             count4=$((makefile_count++));
-            makefile=$($SUDO_FIND $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f -path "*/$(dirname ${f})*" -name "$(basename ${i})" -print -quit) 2>/dev/null;
+            makefile=$(find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f -path "*/$(dirname ${f})*" -name "$(basename ${i})" -print -quit) 2>/dev/null;
             echo -e "\n\n###### REMAKE ERROR ANALYZER ($count4) ######\n";
             for m in ${makefile[@]}; do
               echo -e "\n\n###### ANALYZING FOR ERROR(S) ($count4) ######\n";
@@ -116,14 +114,14 @@ runs:
             for f in ${files[@]}; do
               count5=$((file_count++));
               echo -e "\n###### FILE PATH ($count5) ######\n";
-              $SUDO_FIND $(dirname ${f}) -type f -name $(basename ${f}) -print;
+              find $(dirname ${f}) -type f -name $(basename ${f}) -print;
               echo -e "\n###### FILE CONTENT ($count5) ######\n";
-              $SUDO_FIND $(dirname ${f}) -type f -name $(basename ${f}) -exec cat {} \;
+              find $(dirname ${f}) -type f -name $(basename ${f}) -exec cat {} \;
             done;
             echo -e "Total number of ${{ inputs.filename }} file(s) checked is: $count5\n";
             echo -e "Scanning Completed!\nCheckfile Exiting!\n .....\n";
         elif [ ${file_type} = ${{ inputs.filename }} ]; then
-          finder=$($SUDO_FIND ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.cpp" -o -name "*.cpp" | xargs grep -l "${{ inputs.filename }}");
+          finder=$(find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.cpp" -o -name "*.cpp" | xargs grep -l "${{ inputs.filename }}");
           if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
             counter1=$( echo -e "${finder}" | grep -c "$" );
             echo -e "\n###### ($counter1) CONTENT MATCH(S) FOUND IN C++ FILES ######\n";
@@ -131,7 +129,7 @@ runs:
           else
             echo -e "\n###### NOTHING FOUND IN C++ FILES ######\n";
           fi;
-          finder=$($SUDO_FIND ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.h" -o -name "*.h" | xargs grep -l "${{ inputs.filename }}");
+          finder=$(find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.h" -o -name "*.h" | xargs grep -l "${{ inputs.filename }}");
           if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
             counter2=$( echo -e "${finder}" | grep -c "$" );
             echo -e "\n###### ($counter2) CONTENT MATCH(S) FOUND IN HEADER FILES ######\n";
@@ -139,7 +137,7 @@ runs:
           else
             echo -e "\n###### NOTHING FOUND IN HEADER FILES ######\n";
           fi;
-          finder=$($SUDO_FIND ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.c" -o -name "*.c" | xargs grep -l "${{ inputs.filename }}");
+          finder=$(find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.c" -o -name "*.c" | xargs grep -l "${{ inputs.filename }}");
           if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
             counter3=$( echo -e "${finder}" | grep -c "$" );
             echo -e "\n###### ($counter3) CONTENT MATCH(S) FOUND IN C FILES ######\n";
@@ -147,7 +145,7 @@ runs:
           else
             echo -e "\n###### NOTHING FOUND IN C FILES ######\n";
           fi;
-          finder=$($SUDO_FIND ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.sh" -o -name "*.sh" | xargs grep -l "${{ inputs.filename }}");
+          finder=$(find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.sh" -o -name "*.sh" | xargs grep -l "${{ inputs.filename }}");
           if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
             counter4=$( echo -e "${finder}" | grep -c "$" );
             echo -e "\n###### ($counter4) CONTENT MATCH(S) FOUND IN SHELL FILES ######\n";
@@ -155,7 +153,7 @@ runs:
           else
             echo -e "\n###### NOTHING FOUND IN SHELL FILES ######\n";
           fi;
-          finder=$($SUDO_FIND ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.mk" -o -name "*.mk" -o -iname "Makefile" | xargs grep -l "${{ inputs.filename }}");
+          finder=$(find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.mk" -o -name "*.mk" -o -iname "Makefile" | xargs grep -l "${{ inputs.filename }}");
           if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
             counter5=$( echo -e "${finder}" | grep -c "$" );
             echo -e "\n###### ($counter5) CONTENT MATCH(S) FOUND IN MAKE FILES ######\n";
@@ -169,6 +167,130 @@ runs:
         fi;
       shell: bash
       continue-on-error: true
+
+    - name: Check Filename
+      if: inputs.filename != '' && inputs.rootdir == true
+      run: |
+        export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
+        files=$(sudo find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "${{ inputs.filename }}" -o -name "${{ inputs.filename }}" -print);
+        file_type=$(echo ${{ inputs.filename }} | sed 's/.*\.\([^.]*\)$/\1/');
+        file_count=1
+        include_count=1
+        makefile_count=1
+        shellcheck_count=1
+        if [ ${file_type} = 'h' ] || [ ${file_type} = 'c' ] || [ ${file_type} = 'cpp' ] && [[ -n ${files} ]]; then
+            echo -e "\nFound File Path(s): \n${files}\n";
+            for f in ${files[@]}; do
+              count1=$((file_count++));
+              echo -e "\n###### FILE PATH ($count1) ######\n";
+              sudo find $(dirname ${f}) -type f -name $(basename ${f}) -print;
+              echo -e "\n###### FILE CONTENT ($count1) ######\n";
+              sudo find $(dirname ${f}) -type f -name $(basename ${f}) -exec cat {} \; 
+              echo -e "\n\n###### CPPCHECK ERROR ANALYZER ($count1) ######\n";
+              cppcheck --verbose --force --enable=all --suppress=missingIncludeSystem --std=c++11 --report-progress --quiet ${f}
+              includes=$(sudo find $(dirname ${f}) -name $(basename ${f}) -exec sed -n 's/^#include <\(.*\)>/\1/p; s/^#include "\(.*\)"/\1/p' {} \;)      
+              if [[ -n ${includes} ]]; then
+                echo -e "\nFound Include Path(s): \n${includes}\n";
+                for i in ${includes[@]}; do
+                  count2=$((include_count++));
+                  header=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f -path "*/$(dirname ${i})*" -name "$(basename ${i})" -o -name "$(basename ${i})" -print -quit) 2>/dev/null;
+                  if [[ -f ${header} ]]; then
+                    echo -e "\n###### CPPCHECK HEADER FILE ($count2) ######\n${i}\n";
+                    cppcheck --verbose --force --enable=all --std=c++11 --report-progress --suppress=missingIncludeSystem ${header} ${f}
+                  else
+                    echo -e "\n###### CPPCHECK ANALYZED ($(expr $count2 - 1)) HEADER FILE(S) ######\n";
+                    break;
+                  fi;
+                done;
+              fi;
+              done;
+          echo -e "Total number of ${{ inputs.filename }} file(s) checked is: $count1\n";
+          echo -e "Total number of include file(s) checked is: $count2\n";
+          echo -e "Scanning Completed!\nCppcheck Exiting!\n .....\n";
+        elif [ ${file_type} = 'sh' ] && [[ -n ${files} ]]; then
+          for f in ${files[@]}; do
+            count3=$((shellcheck_count++));
+            shellcheck=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f -path "*/$(dirname ${f})*" -name "$(basename ${i})" -print -quit) 2>/dev/null;
+            echo -e "\n\n###### SHELLCHECK ERROR ANALYZER ($count3) ######\n";
+            for s in ${shellcheck[@]}; do
+              echo -e "\n\n###### ANALYZING FOR ERROR(S) ($count3) ######\n";
+              shellcheck --norc --severity=error --external-sources --check-sourced ${f} ${s};
+            done;
+          done;
+          echo -e "Total number of ${{ inputs.filename }} file(s) checked is: $count3\n";
+          echo -e "Total number of include file(s) checked is: $count3\n";
+          echo -e "Scanning Completed!\nShellcheck Exiting!\n .....\n";
+        elif [ ${file_type} = 'Makefile' ] || [ ${file_type} = 'makefile' ] || [ ${file_type} = 'mk' ] && [[ -n ${files} ]]; then
+          for f in ${files[@]}; do
+            count4=$((makefile_count++));
+            makefile=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f -path "*/$(dirname ${f})*" -name "$(basename ${i})" -print -quit) 2>/dev/null;
+            echo -e "\n\n###### REMAKE ERROR ANALYZER ($count4) ######\n";
+            for m in ${makefile[@]}; do
+              echo -e "\n\n###### ANALYZING FOR ERROR(S) ($count4) ######\n";
+              remake -n -v --debug --keep-going -I $(dirname ${m}) ${f};
+            done;
+          done;
+          echo -e "Total number of ${{ inputs.filename }} file(s) checked is: $count4\n";
+          echo -e "Total number of include file(s) checked is: $count4\n";
+          echo -e "Scanning Completed!\nRemake Exiting!\n .....\n";
+        elif [[ -n ${files} ]]; then
+            for f in ${files[@]}; do
+              count5=$((file_count++));
+              echo -e "\n###### FILE PATH ($count5) ######\n";
+              sudo find $(dirname ${f}) -type f -name $(basename ${f}) -print;
+              echo -e "\n###### FILE CONTENT ($count5) ######\n";
+              sudo find $(dirname ${f}) -type f -name $(basename ${f}) -exec cat {} \;
+            done;
+            echo -e "Total number of ${{ inputs.filename }} file(s) checked is: $count5\n";
+            echo -e "Scanning Completed!\nCheckfile Exiting!\n .....\n";
+        elif [ ${file_type} = ${{ inputs.filename }} ]; then
+          finder=$(sudo find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.cpp" -o -name "*.cpp" | xargs grep -l "${{ inputs.filename }}");
+          if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
+            counter1=$( echo -e "${finder}" | grep -c "$" );
+            echo -e "\n###### ($counter1) CONTENT MATCH(S) FOUND IN C++ FILES ######\n";
+            echo -e "\n${finder}\n";
+          else
+            echo -e "\n###### NOTHING FOUND IN C++ FILES ######\n";
+          fi;
+          finder=$(sudo find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.h" -o -name "*.h" | xargs grep -l "${{ inputs.filename }}");
+          if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
+            counter2=$( echo -e "${finder}" | grep -c "$" );
+            echo -e "\n###### ($counter2) CONTENT MATCH(S) FOUND IN HEADER FILES ######\n";
+            echo -e "\n${finder}\n";
+          else
+            echo -e "\n###### NOTHING FOUND IN HEADER FILES ######\n";
+          fi;
+          finder=$(sudo find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.c" -o -name "*.c" | xargs grep -l "${{ inputs.filename }}");
+          if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
+            counter3=$( echo -e "${finder}" | grep -c "$" );
+            echo -e "\n###### ($counter3) CONTENT MATCH(S) FOUND IN C FILES ######\n";
+            echo -e "\n${finder}\n";
+          else
+            echo -e "\n###### NOTHING FOUND IN C FILES ######\n";
+          fi;
+          finder=$(sudo find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.sh" -o -name "*.sh" | xargs grep -l "${{ inputs.filename }}");
+          if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
+            counter4=$( echo -e "${finder}" | grep -c "$" );
+            echo -e "\n###### ($counter4) CONTENT MATCH(S) FOUND IN SHELL FILES ######\n";
+            echo -e "\n${finder}\n";
+          else
+            echo -e "\n###### NOTHING FOUND IN SHELL FILES ######\n";
+          fi;
+          finder=$(sudo find ${{ env.FILE_PATH }} -type f -path "*/${{ inputs.dirname }}/*" -name "*.mk" -o -name "*.mk" -o -iname "Makefile" | xargs grep -l "${{ inputs.filename }}");
+          if [[ -n ${finder} ]] && [ $? -eq 0 ]; then
+            counter5=$( echo -e "${finder}" | grep -c "$" );
+            echo -e "\n###### ($counter5) CONTENT MATCH(S) FOUND IN MAKE FILES ######\n";
+            echo -e "\n${finder}\n";
+          else
+            echo -e "\n###### NOTHING FOUND IN MAKE FILES ######\n";
+          fi;
+          echo -e "Scanning Completed!\nText Locator Exiting!\n .....\n"        
+        else
+          echo -e "\n###### ${{ inputs.filename }} NOT FOUND IN CHECKED FILES ######\n";
+        fi;
+      shell: bash
+      continue-on-error: true
+
 
     - name: Publish Checked Report
       if: inputs.publish != ''
