Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -82,12 +82,12 @@ runs:
         /usr/bin/echo ''
         if ${{ inputs.rootdir }}; then
           /usr/bin/echo -e "\n####################\nNOTE: Search default directory ( ~/ )\n####################\n";
-          /usr/bin/echo "FILE_PATH=/" >> ${GITHUB_ENV};
-          /usr/bin/echo "FILE_FOUND=0" >> ${GITHUB_ENV};
+          /usr/bin/echo "FILE_PATH=/" >> "${GITHUB_ENV}";
+          /usr/bin/echo "FILE_FOUND=0" >> "${GITHUB_ENV}";
         else
           /usr/bin/echo -e "\n####################\nNOTE: Search default directory ( ${GITHUB_WORKSPACE} )\n####################\n";
-          /usr/bin/echo "FILE_PATH=${GITHUB_WORKSPACE}" >> ${GITHUB_ENV};
-          /usr/bin/echo "FILE_FOUND=0" >> ${GITHUB_ENV};
+          /usr/bin/echo "FILE_PATH=${GITHUB_WORKSPACE}" >> "${GITHUB_ENV}";
+          /usr/bin/echo "FILE_FOUND=0" >> "${GITHUB_ENV}";
         fi;
       shell: bash
       continue-on-error: false
@@ -105,7 +105,7 @@ runs:
         makefile_count=1
         shellcheck_count=1
         if [[ $(/usr/bin/echo "${file_type}" | egrep "c*|h*|t*") ]] && [[ -n ${files} ]]; then
-          /usr/bin/echo "FILE_FOUND=1" >> ${GITHUB_ENV};
+          /usr/bin/echo "FILE_FOUND=1" >> "${GITHUB_ENV}";
           /usr/bin/echo -e "\nFound File Path(s):\n${files}\n";
           for f in ${files[@]}; do
             count1=$((file_count++));
@@ -153,7 +153,7 @@ runs:
           /usr/bin/echo -e "Total number of included file(s) checked is: $count2\n";
           /usr/bin/echo -e "Scanning Completed!\nCppcheck Exiting!\n .....\n";
         elif [[ $(/usr/bin/echo "${file_type}" | grep -i "sh") ]] && [[ -n ${files} ]]; then
-          /usr/bin/echo "FILE_FOUND=1" >> ${GITHUB_ENV};
+          /usr/bin/echo "FILE_FOUND=1" >> "${GITHUB_ENV}";
           for f in ${files[@]}; do
             count3=$((shellcheck_count++));
             /usr/bin/echo -e "\n\n####################\nSHELLCHECK ANALYZING $(basename ${s}) FOR ERROR(S) ($count3)\n####################\n\n";
@@ -168,12 +168,12 @@ runs:
           /usr/bin/echo -e "\nTotal number of ${{ inputs.filename }} file(s) checked is: $count3\n";
           /usr/bin/echo -e "Scanning Completed!\nShellcheck Exiting!\n .....\n";
         elif [[ $(/usr/bin/echo "${file_type}" | egrep -i "mk|.*Makefile|Makefile") ]] && [[ -n ${files} ]]; then
-          /usr/bin/echo "FILE_FOUND=1" >> ${GITHUB_ENV};
+          /usr/bin/echo "FILE_FOUND=1" >> "${GITHUB_ENV}";
           for f in ${files[@]}; do
             count4=$((makefile_count++));
-            /usr/bin/echo -e "\n####################\nCHECKMAKE ANALYZING $(basename ${f}) FOR ERROR(S) ($count4)\n####################\n";
+            /usr/bin/echo -e "\n\n####################\nCHECKMAKE ANALYZING $(basename ${f}) FOR ERROR(S) ($count4)\n####################\n\n";
             checkmake "${f}" || /usr/bin/echo -e "\n####################\nCHECKMAKE FOUND ERROR(S)\n####################\n";
-            [ $? -eq 0 ] && /usr/bin/echo -e "\n####################\nCHECKMAKE NO ERRORS FOUND ( ${f} )\n####################\n";
+            [ $? -eq 0 ] && /usr/bin/echo -e "\n####################\nCHECKMAKE NO ERRORS FOUND $(basename ${f})\n####################\n";
             if ${{ inputs.content }}; then
               /usr/bin/echo -e "\n####################\n\tFILE CONTENT ($count4)\n####################\n\n";
               batcat --paging=never --theme=GitHub --show-all --color=always --style=full "${f}";
@@ -183,11 +183,11 @@ runs:
           /usr/bin/echo -e "\nTotal number of ${{ inputs.filename }} file(s) checked is: $count4\n";
           /usr/bin/echo -e "Scanning Completed!\nCheckMake Exiting!\n .....\n";
         elif [[ -n ${files} ]]; then
-            /usr/bin/echo "FILE_FOUND=1" >> ${GITHUB_ENV};
+            /usr/bin/echo "FILE_FOUND=1" >> "${GITHUB_ENV}";
             for f in ${files[@]}; do
               count5=$((file_count++));
               /usr/bin/echo -e "\n####################\n\tFILE PATH ($count5)\n####################\n";
-              /usr/bin/echo $(dirname $(find $(dirname ${f}) -type f -name $(basename ${f}) -print));
+              /usr/bin/echo "$(dirname $(find $(dirname ${f}) -type f -name $(basename ${f}) -print))";
               if ${{ inputs.content }}; then
                 /usr/bin/echo -e "\n####################\n\tFILE CONTENT ($count5)\n####################\n\n";
                 batcat --paging=never --theme=GitHub --show-all --color=always --style=full "${f}";
@@ -265,7 +265,7 @@ runs:
         makefile_count=1
         shellcheck_count=1
         if [[ $(/usr/bin/echo "${file_type}" | egrep "c*|h*|t*") ]] && [[ -n ${files} ]]; then
-          /usr/bin/echo "FILE_FOUND=1" >> ${GITHUB_ENV};
+          /usr/bin/echo "FILE_FOUND=1" >> "${GITHUB_ENV}";
           /usr/bin/echo -e "\nFound File Path(s):\n${files}\n";
           for f in ${files[@]}; do
             count1=$((file_count++));
@@ -313,12 +313,12 @@ runs:
           /usr/bin/echo -e "Total number of included file(s) checked is: $count2\n";
           /usr/bin/echo -e "Scanning Completed!\nCppcheck Exiting!\n .....\n";
         elif [[ $(/usr/bin/echo "${file_type}" | grep -i "sh") ]] && [[ -n ${files} ]]; then
-          /usr/bin/echo "FILE_FOUND=1" >> ${GITHUB_ENV};
+          /usr/bin/echo "FILE_FOUND=1" >> "${GITHUB_ENV}";
           for f in ${files[@]}; do
             count3=$((shellcheck_count++));
             /usr/bin/echo -e "\n\n####################\nSHELLCHECK ANALYZING $(basename ${s}) FOR ERROR(S) ($count3)\n####################\n\n";
             shellcheck --norc --severity=error "${f}" || /usr/bin/echo -e "\n####################\nSHELLCHECK FOUND ERROR(S)\n####################\n";
-            [ $? -eq 0 ] && /usr/bin/echo -e "\n####################\nSHELLCHECK NO ERRORS FOUND ( ${f} )\n####################\n"
+            [ $? -eq 0 ] && /usr/bin/echo -e "\n####################\nSHELLCHECK NO ERRORS FOUND $(basename ${f})\n####################\n"
             if ${{ inputs.content }}; then
               /usr/bin/echo -e "\n####################\n\tFILE CONTENT ($count3)\n####################\n\n";
               batcat --paging=never --theme=GitHub --show-all --color=always --style=full "${f}";
@@ -328,12 +328,12 @@ runs:
           /usr/bin/echo -e "\nTotal number of ${{ inputs.filename }} file(s) checked is: $count3\n";
           /usr/bin/echo -e "Scanning Completed!\nShellcheck Exiting!\n .....\n";
         elif [[ $(/usr/bin/echo "${file_type}" | egrep -i "mk|.*Makefile|Makefile") ]] && [[ -n ${files} ]]; then
-          /usr/bin/echo "FILE_FOUND=1" >> ${GITHUB_ENV};
+          /usr/bin/echo "FILE_FOUND=1" >> "${GITHUB_ENV}";
           for f in ${files[@]}; do
             count4=$((makefile_count++));
             /usr/bin/echo -e "\n####################\nCHECKMAKE ANALYZING $(basename ${f}) FOR ERROR(S) ($count4)\n####################\n";
             checkmake "${f}" || /usr/bin/echo -e "\n####################\nCHECKMAKE FOUND ERROR(S)\n####################\n";
-            [ $? -eq 0 ] && /usr/bin/echo -e "\n####################\nCHECKMAKE NO ERRORS FOUND ( ${f} )\n####################\n";
+            [ $? -eq 0 ] && /usr/bin/echo -e "\n####################\nCHECKMAKE NO ERRORS FOUND $(basename ${f})\n####################\n";
             if ${{ inputs.content }}; then
               /usr/bin/echo -e "\n####################\n\tFILE CONTENT ($count4)\n####################\n\n";
               batcat --paging=never --theme=GitHub --show-all --color=always --style=full "${f}";
@@ -343,11 +343,11 @@ runs:
           /usr/bin/echo -e "\nTotal number of ${{ inputs.filename }} file(s) checked is: $count4\n";
           /usr/bin/echo -e "Scanning Completed!\nCheckMake Exiting!\n .....\n";
         elif [[ -n ${files} ]]; then
-          /usr/bin/echo "FILE_FOUND=1" >> ${GITHUB_ENV};
+          /usr/bin/echo "FILE_FOUND=1" >> "${GITHUB_ENV}";
           for f in ${files[@]}; do
             count5=$((file_count++));
             /usr/bin/echo -e "\n####################\n\tFILE PATH ($count5)\n####################\n";
-            /usr/bin/echo $(dirname $(sudo find $(dirname ${f}) -type f -name $(basename ${f}) -print));
+            /usr/bin/echo "$(dirname $(sudo find $(dirname ${f}) -type f -name $(basename ${f}) -print))";
             if ${{ inputs.content }}; then
               /usr/bin/echo -e "\n####################\n\tFILE CONTENT ($count5)\n####################\n\n";
               batcat --paging=never --theme=GitHub --show-all --color=always --style=full "${f}";
