Add files via upload

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -214,57 +214,41 @@ runs:
               echo -e "\n####################\n\tFILE CONTENT (${count1})\n####################\n";
               sudo find $(dirname ${f}) -type f -name $(basename ${f}) -exec batcat --theme=ansi --paging=never --show-all --color=always --style=full "{}" \;
             fi;
-              echo -e "\n\n####################\nCLANG-TIDY ERROR ANALYZER (${count1})\n####################\n\n";
-              clang-tidy "${f}" --fix --fix-errors --fix-notes --config-file="${clang_file}" |& tee -a "${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log" || echo -e "\n####################\nCLANG-TIDY FOUND ERROR(S)\n####################\n" && file_error=1;
-              if [[ ${file_error} == 0 ]]; then
+            echo -e "\n\n####################\nCLANG-TIDY ERROR ANALYZER (${count1})\n####################\n\n";
+            clang-tidy "${f}" --config-file="${clang_file}" |& tee -a "${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log" || echo -e "\n####################\nCLANG-TIDY FOUND ERROR(S)\n####################\n" && file_error=1;
+            if [[ ${file_error} == 0 ]]; then
                 echo -e "\n####################\nCHECKMAKE NO ERRORS FOUND ${f}\n####################\n";
-              fi;
+            fi;
             if ${{ inputs.include }}; then
               includes=$(sudo find $(dirname ${f}) -name $(basename ${f}) -exec sed -n 's/^#include <\(.*\)>/\1/p; s/^#include "\(.*\)"/\1/p' "{}" \;);
-              included1='include_file.txt'
-              included2='parameters_file'
-              if [[ -f "$(dirname ${f})/${included2}" ]]; then
-                rm -vf "$(dirname ${f})/${included1}" "$(dirname ${f})/${included2}" 2>/dev/null;
-              fi;
               if [[ -n ${includes} ]]; then
                 echo -e "\nFound Include Path(s):\n${includes}\n";
                 for i in ${includes[@]}; do
                   count2=$((include_count++));
                   header=$(sudo find $(echo $(dirname ${f}) | cut -d/ -f1-8) -type f \( -path "*/$(dirname ${i})/*" -o -path "*" \) -name "$(basename ${i})" -print -quit) 2>/dev/null;
-                  for h in "${header[@]}"; do
-                    echo "$(dirname ${h})" >> "$(dirname ${f})/${included1}";
-                  done;
-                done;
-                if [[ -f "$(dirname ${f})/${included1}" ]]; then
-                  awk '!seen[$0]++' "$(dirname ${f})/${included1}" > "$(dirname ${f})/${included2}";
-                fi;
-                if [[ -f ${header} ]] && [[ -f "$(dirname ${f})/${included2}" ]]; then
-                  included3=$(dirname ${f})/${included2}
-                  if ${{ inputs.content }}; then
-                    echo -e "\n####################\n\tFILE CONTENT (${count2})\n####################\n";
-                    batcat --theme=ansi --paging=never --show-all --color=always --style=full "${included3}";
+                  include=$( "${header}" | while read path; do echo -n " -I $path"; done);
+                  if [[ -f ${header} ]] && [[ -n "${include}" ]]; then
+                    if ${{ inputs.content }}; then
+                      echo -e "\n####################\n\tFILE CONTENT (${count2})\n####################\n";
+                      batcat --theme=ansi --paging=never --show-all --color=always --style=full "${included3}";
+                    fi;
+                    echo -e "\n\n####################\nCLANG-TIDY INCLUDED HEADER FILES (${count2})\n####################\n\nFinal File: ${i}\n\n";
+                    clang-tidy "${f}" --config-file="${clang_file}" -- "${include}" |& tee -a "${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log" || echo -e "\n####################\nCLANG-TIDY FOUND ERROR(S)\n####################\n" && file_error=1;
+                    if [[ ${file_error} == 0 ]]; then
+                      echo -e "\n####################\nCHECKMAKE NO ERRORS FOUND ${f}\n####################\n";
+                    fi;
+                  else
+                    echo -e "\n\n####################\nCLANG-TIDY INCLUDED HEADER(S) FOR $(basename ${f}) NOT FOUND\n####################\n\n";
                   fi;
-                  echo -e "\n\n####################\nCLANG-TIDY INCLUDED HEADER FILES (${count2})\n####################\n\nFinal File: ${i}\n\n";
-                  clang-tidy "${included3}" --fix --fix-errors --fix-notes --config-file="${clang_file}" |& tee -a "${GITHUB_WORKSPACE}/${{ inputs.filename }}_error.log" || echo -e "\n####################\nCLANG-TIDY FOUND ERROR(S)\n####################\n" && file_error=1;
-                  if [[ ${file_error} == 0 ]]; then
-                    echo -e "\n####################\nCHECKMAKE NO ERRORS FOUND ${f}\n####################\n";
-                  fi;
-                else
-                  echo -e "\n\n####################\nCLANG-TIDY INCLUDED HEADER(S) FOR $(basename ${f}) NOT FOUND\n####################\n\n";
                 fi;
               fi;
-            fi;
-          done;
-          if [[ -f "$(dirname ${f})/${included2}" ]]; then
-            echo ' ';
-            rm -vf "$(dirname ${f})/${included1}" "$(dirname ${f})/${included2}" 2>/dev/null;
+            done;
+            echo -e "\nTotal number of ${{ inputs.filename }} file(s) checked is: ${count1}\n";
+            echo -e "Total number of included file(s) checked is: ${count2}\n";
+            echo -e "Scanning Completed!\nCppcheck Exiting!\n .....\n";
+          else
+            echo -e "\n####################\nFINISHED SEARCHING C/C++ FILES\nNO ${{ inputs.filename }} FOUND\n####################\n";
           fi;
-          echo -e "\nTotal number of ${{ inputs.filename }} file(s) checked is: ${count1}\n";
-          echo -e "Total number of included file(s) checked is: ${count2}\n";
-          echo -e "Scanning Completed!\nCppcheck Exiting!\n .....\n";
-        else
-          echo -e "\n####################\nFINISHED SEARCHING C/C++ FILES\nNO ${{ inputs.filename }} FOUND\n####################\n";
-        fi;
       shell: bash
       continue-on-error: true
 
